### ISSUE TITLE
Navigation features

### ISSUE THREAD

**Issue by gugoan** [MelleDijkstra/yii2-slideshow#1]
Hello, beautiful work, you made friends!
How do I use properties to include navigation features?

[https://github.com/nolimits4web/Swiper/blob/master/demos/14-nav-arrows.html](https://github.com/nolimits4web/Swiper/blob/master/demos/14-nav-arrows.html)

**Comment by melledijkstra** [comment]
Hey @gugoan,
You should be able to use the `clientOptions` like so:
~~~php
...
"clientOptions" => [
    "pagination" => ".swiper-pagination",
    "paginationClickable" => true,
    "nextButton" => ".swiper-button-next",
    "prevButton" => ".swiper-button-prev",
    "spaceBetween" => 30,
],
...
~~~
If not then mention me
